### ISSUE TITLE
anyway to contact you to learn how to flash T-echo from VSCODE?

### ISSUE THREAD

**Issue by richonguzman** [cfr34k/t-echo-lora-aprs#20]
anyway to contact you to learn how to flash T-echo from VSCODE?

maybe on telegram with my @ user ?

**Comment by cfr34k** [comment]
Hi, I don't use VSCode and therefore can't help you with it, sorry.

However, this project uses a (more or less) simple Makefile that generates `_build/nrf52840_xxaa.uf2`, which you can then copy to your T-Echo using the bootloader. Maybe you can find a way to automate that. Good luck!

**Comment by richonguzman** [comment]
eventually I did manage to be able to flash it from VSCODE so it seems I will try to  add all of my tracker firmware to test it more and more this awesome board...
