### ISSUE TITLE
Problems flashing the firmware.

### ISSUE THREAD

**Issue by IV3JYV** [cfr34k/t-echo-lora-aprs#25]
Hi,

I tried to flash the firmware copying the UF2 file in the techoboot folder but when it is copying the file at a certain percentage the device is disconnected and nothing is happening. When double clicked the reset button the mass storage device is reappearing but always with current.udf2, therefore the new firmnware is not installed. 
Any idea on how to flash it in an alternative way? I tried all steps many times without success.

**Comment by DayleDrinkwater** [comment]
Hi, have you tried with a different USB cable? Also even when successful it will be named current.uf2 anyway

M0OUE

**Comment by cfr34k** [comment]
M0OUE is right, you will always only see current.uf2.

Additionally, are you using the `with-sd` version if you are installing my firmware for the first time? This one: https://github.com/cfr34k/t-echo-lora-aprs/releases/download/v1.1/t-echo-lora-aprs-with-sd-v1.1.uf2 . It includes the bluetooth stack which has to be installed for my firmware to work.

**Comment by IV3JYV** [comment]
OK with the file at the link the system is rebooting correctly. Now hopefully I can set the device in the right way.

**Comment by IV3JYV** [comment]
Many thanks
